#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


xset -dpms # Disables Energy Star features
xset s off # Disables screen saver
xrandr --output HDMI-A-1 --mode 1920x1080 --left-of DisplayPort-1
xsetroot -solid '#5A8E3A'
mpd &
mpd-discord-rpc &
sudo systemctl start php-fpm &
sudo systemctl start nginx &
picom --config ~/.config/picombsp.conf &
nitrogen --restore &
systemctl --user start spotifyd.service &
pasystray &
~/.config/polybar/bsplaunch.sh
# glava -d -a fifo &

bspc monitor HDMI-A-1 -d 1 2 3
bspc monitor DisplayPort-1 -d 4 5 6 7 8 9 10 11 12


bspc config border_width         2.5
bspc config window_gap          10
bspc config top_padding         -5

bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color		      "#282828"
bspc config active_border_color	          "#282828"
bspc config focused_border_color	      "#d3869b"
bspc config presel_feedback_color	      "#458588"
bspc config urgent_border_color 	      "#458588"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiling

bspc rule -a Thunderbird desktop=9
bspc rule -a Lutris desktop=6
bspc rule -a Thunar desktop=8
bspc rule -a Steam desktop=6
bspc rule -a firefox desktop=5
bspc rule -a code-oss desktop=4
bspc rule -a discord desktop=3
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbsp_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbsp_HDMI-A-1)


