#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-A-1 --mode 1920x1080 --left-of DisplayPort-1
xsetroot -solid '#5A8E3A'
picom --config ~/.config/picombsp.conf &
nitrogen --restore &
systemctl --user start spotifyd.service &
~/.config/polybar/bsplaunch.sh

bspc monitor HDMI-A-1 -d 1 2 3
bspc monitor DisplayPort-1 -d 4 5 6 7 8 9 10 11 12


bspc config border_width         2.5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color		      "#ebdbb2"
bspc config active_border_color	          "#ebdbb2"
bspc config focused_border_color	      "#fabd2f"
bspc config presel_feedback_color	      "#fabd2f"
bspc config urgent_border_color 	      "#fb4934"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbsp_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-mainbsp_HDMI-A-1)
